spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: c181a615-8ad1-4cb2-9aa0-f2b927712ab8
            client-secret: 1-87H-oE1wPb44s2K.Nl3B8Z8a9NW3v_wA
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/discovery/v2.0/keys
  h2:
    console:
      enabled: true

application:
  smoketest:
    enabled: true

  authentication:
    lockout-count: 3
    microsoft:
      linktext: login with justice email.

  # test key which doesn't send emails, but is automatically accepted by notify
  notify:
    key: testkey-992308b2-1e8f-4667-816b-8bdde781a4ac-9c211cf4-96d1-4c30-848b-8f172bca0b41

  support.url: https://localhost:9101/feedback-and-support

delius:
  enabled: false
  endpoint:
    url: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    timeout: 1s

  client:
    client-id: delius-auth-api-client
    client-secret: delius-auth-api-client
  roles:
    mappings:
      TEST_ROLE:
        - 'ROLE_LICENCE_RO'
        - 'ROLE_GLOBAL_SEARCH'

tokenverification:
  enabled: false
  endpoint:
    url: http://localhost:8100
    timeout: 1s

  client:
    client-id: token-verification-auth-api-client
    client-secret: token-verification-auth-api-client

