spring:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      hbm2ddl:
        auto: create

auth:
  flyway:
    locations: db/migration,db/data/sample
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
