spring:
  profiles:
    include: dev-config,auth-seed,nomis-seed

delius:
  endpoint.url: http://localhost:8099
  client:
    client-id: delius-auth-api-client
    client-secret: delius-auth-api-client
