spring:
  h2:
    console:
      enabled: true

application:
  smoketest:
    enabled: true

  authentication:
    lockout-count: 3

  # test key which doesn't send emails, but is automatically accepted by notify
  notify:
    key: testkey-992308b2-1e8f-4667-816b-8bdde781a4ac-9c211cf4-96d1-4c30-848b-8f172bca0b41


graceful:
  shutdown:
    enabled: false
