spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        show_sql: false
        jdbc:
          fetch_size: 100

auth:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: false
