spring:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: dummy
            client-secret: dummy
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/discovery/v2.0/keys

application:
  smoketest:
    enabled: true

  authentication:
    lockout-count: 3
    show-azure-link: true

  # test key which doesn't send emails, but is automatically accepted by notify
  notify:
    key: testkey-992308b2-1e8f-4667-816b-8bdde781a4ac-9c211cf4-96d1-4c30-848b-8f172bca0b41

delius:
  enabled: false
  endpoint:
    url: http://localhost:8099
    timeout: 1s

  client:
    client-id: delius-auth-api-client
    client-secret: delius-auth-api-client
  roles:
    mappings:
      TEST_ROLE:
        - 'ROLE_LICENCE_RO'
        - 'ROLE_GLOBAL_SEARCH'

tokenverification:
  enabled: false
  endpoint:
    url: http://localhost:8100
    timeout: 1s

  client:
    client-id: token-verification-auth-api-client
    client-secret: token-verification-auth-api-client

