spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${auth.azureoidc.client_id}
            client-secret: ${auth.azureoidc.client_secret}
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          microsoftb2c:
            client-id: ${auth.azureb2c.client_id}
            client-secret: ${auth.azureb2c.client_secret}
            scope: openid, https://mojodevlb2c.onmicrosoft.com/37e7a745-0369-46ec-8a6c-001ebc6687c9/Test.Read
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/discovery/v2.0/keys
          microsoftb2c:
            authorization-uri: https://mojodevlb2c.b2clogin.com/mojodevlb2c.onmicrosoft.com/${auth.azureb2c.user_flow}/oauth2/v2.0/authorize
            token-uri: https://mojodevlb2c.b2clogin.com/mojodevlb2c.onmicrosoft.com/${auth.azureb2c.user_flow}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://mojodevlb2c.b2clogin.com/mojodevlb2c.onmicrosoft.com/${auth.azureb2c.user_flow}/discovery/v2.0/keys

application:
  authentication:
    microsoft:
      linktext: Sign in with a justice.gov.uk email
    microsoftb2c:
      linktext: Sign in with an Azure B2C account
