spring:
  security:
    oauth2:
      client:
        registration:
          microsoft:
            client-id: ${auth.azureoidc.client_id}
            client-secret: ${auth.azureoidc.client_secret}
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/${auth.azureoidc.tenant_id}/discovery/v2.0/keys

application:
  authentication:
    microsoft:
      linktext: Log in with a justice.gov.uk email
