spring:

  h2:
    console:
      enabled: true

nomis:
  flyway:
    locations: db/nomis

auth:
  flyway:
    locations: db/migration,db/data/sample
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
