spring:
  h2:
    console:
      enabled: true

application:
  smoketest:
    enabled: true

  authentication:
    lockout-count: 3

  # test key which doesn't send emails, but is automatically accepted by notify
  notify:
    key: testkey-992308b2-1e8f-4667-816b-8bdde781a4ac-9c211cf4-96d1-4c30-848b-8f172bca0b41

  support.url: https://localhost:9101/feedback-and-support
  signin.url: http://localhost:9090/auth/login

delius:
  enabled: false
  endpoint:
    url: http://localhost:8099
    timeout: 1s

  client:
    client-id: delius-auth-api-client
    client-secret: delius-auth-api-client
  roles:
    mappings:
      TEST_ROLE:
        - 'ROLE_LICENCE_RO'
        - 'ROLE_GLOBAL_SEARCH'

tokenverification:
  enabled: false
  endpoint:
    url: http://localhost:8100
    timeout: 1s

  client:
    client-id: token-verification-auth-api-client
    client-secret: token-verification-auth-api-client

