CREATE USER ITAG_USER password 'password';

INSERT INTO  STAFF_MEMBERS (STAFF_ID, FIRST_NAME, LAST_NAME) VALUES (1, 'ITAG', 'USER');
INSERT INTO STAFF_USER_ACCOUNTS (username, staff_user_type, staff_id) VALUES ('ITAG_USER', 'GENERAL', 1);

INSERT INTO CASELOADS (CASELOAD_ID, DESCRIPTION, CASELOAD_TYPE) VALUES ('NWEB', 'Magic API Caseload', 'APP');

INSERT INTO OMS_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_SEQ, ROLE_TYPE, ROLE_FUNCTION) VALUES (1, 'OMIC_ADMIN', 'Omic Administrator', 1, 'APP', 'GENERAL');
INSERT INTO OMS_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_SEQ, ROLE_TYPE, ROLE_FUNCTION) VALUES (2, 'LICENCE_CA', 'Licence Case Admin', 2, 'APP', 'GENERAL');

INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, CASELOAD_ID, USERNAME) VALUES (1, 'NWEB', 'ITAG_USER');
INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, CASELOAD_ID, USERNAME) VALUES (2, 'NWEB', 'ITAG_USER');

