create table CASELOADS (
  CASELOAD_ID   VARCHAR2(6)  not null,
  DESCRIPTION   VARCHAR2(40) not null,
  CASELOAD_TYPE VARCHAR2(12),
  primary key (CASELOAD_ID)
);

CREATE INDEX "CASELOADS_NI1"
  ON "CASELOADS" ("CASELOAD_TYPE", "CASELOAD_ID");

CREATE TABLE "OMS_ROLES"
(
  "ROLE_ID"          NUMBER(10, 0)                  NOT NULL,
  "ROLE_NAME"        VARCHAR2(30)                   NOT NULL,
  "ROLE_SEQ"         NUMBER(3, 0)                   NOT NULL,
  "ROLE_CODE"        VARCHAR2(30)                   NOT NULL,
  "PARENT_ROLE_CODE" VARCHAR2(30),
  "ROLE_TYPE"        VARCHAR2(12),
  "ROLE_FUNCTION"    VARCHAR2(12) DEFAULT 'GENERAL' NOT NULL,
  "SYSTEM_DATA_FLAG" VARCHAR2(1) DEFAULT 'N'        NOT NULL,
  CONSTRAINT "OMS_ROLES_UK" UNIQUE ("ROLE_CODE"),
  CONSTRAINT "USER_GROUPS_PK" PRIMARY KEY ("ROLE_ID"),
  CONSTRAINT "OMS_ROLES_OMS_ROLES_FK" FOREIGN KEY ("PARENT_ROLE_CODE")
  REFERENCES "OMS_ROLES" ("ROLE_CODE")
);

CREATE INDEX "OMS_ROLES_NI1"
  ON "OMS_ROLES" ("PARENT_ROLE_CODE");

CREATE TABLE "STAFF_MEMBERS"
(
  "STAFF_ID"   NUMBER(10, 0) NOT NULL,
  "LAST_NAME"  VARCHAR2(35)  NOT NULL,
  "FIRST_NAME" VARCHAR2(35)  NOT NULL,
  "STATUS"     VARCHAR2(12),
  primary key (STAFF_ID)
);

CREATE TABLE PERSONNEL_IDENTIFICATIONS
(
  STAFF_ID              NUMBER(10)   NOT NULL
    CONSTRAINT PERSONNEL_ID_STAFF
    REFERENCES STAFF_MEMBERS,
  IDENTIFICATION_TYPE   VARCHAR2(12) NOT NULL,
  IDENTIFICATION_NUMBER VARCHAR2(32) NOT NULL,
  TEXT_FROM             VARCHAR2(40),
  CONSTRAINT PERSONNEL_IDENTIFICATION_PK
  PRIMARY KEY (STAFF_ID, IDENTIFICATION_TYPE, IDENTIFICATION_NUMBER)
);

CREATE TABLE "STAFF_USER_ACCOUNTS"
(
  "USERNAME"            VARCHAR2(30)  NOT NULL,
  "STAFF_ID"            NUMBER(10, 0) NOT NULL,
  "STAFF_USER_TYPE"     VARCHAR2(12)  NOT NULL,
  "WORKING_CASELOAD_ID" VARCHAR2(6),
  CONSTRAINT "STAFF_USER_ACCOUNT_PK" PRIMARY KEY ("USERNAME"),
  CONSTRAINT "STAFF_USER_ACCOUNT_UK1" UNIQUE ("STAFF_ID", "STAFF_USER_TYPE"),
  CONSTRAINT "STAFF_USER_ACCOUNTS_FK1" FOREIGN KEY ("STAFF_ID")
  REFERENCES "STAFF_MEMBERS" ("STAFF_ID")
);

CREATE INDEX "STAFF_USER_ACCOUNTS_FK1"
  ON "STAFF_USER_ACCOUNTS" ("STAFF_ID");

CREATE TABLE "USER_ACCESSIBLE_CASELOADS"
(
  "CASELOAD_ID" VARCHAR2(6)  NOT NULL,
  "USERNAME"    VARCHAR2(30) NOT NULL,
  "START_DATE"  DATE,
  CONSTRAINT "USER_ACCESSIBLE_CASELOADS_PK" PRIMARY KEY ("CASELOAD_ID", "USERNAME"),
  CONSTRAINT "STAFF_USER_ACCESSIBLE_CLS_FK1" FOREIGN KEY ("USERNAME") REFERENCES "STAFF_USER_ACCOUNTS" ("USERNAME"),
  CONSTRAINT "STAFF_USER_ACCESSIBLE_CLS_FK2" FOREIGN KEY ("CASELOAD_ID") REFERENCES "CASELOADS" ("CASELOAD_ID")
);

CREATE INDEX "USER_ACCESSIBLE_CLS_FK1"
  ON "USER_ACCESSIBLE_CASELOADS" ("USERNAME");
CREATE INDEX "USER_ACCESSIBLE_CLS_FK2"
  ON "USER_ACCESSIBLE_CASELOADS" ("CASELOAD_ID");


CREATE TABLE "USER_CASELOAD_ROLES"
(
  "ROLE_ID"     NUMBER(10, 0) NOT NULL,
  "USERNAME"    VARCHAR2(30)  NOT NULL,
  "CASELOAD_ID" VARCHAR2(6)   NOT NULL,
  CONSTRAINT "USER_CASELOAD_ROLES_PK" PRIMARY KEY ("USERNAME", "CASELOAD_ID", "ROLE_ID"),
  CONSTRAINT "USER_CASELOAD_ROLES_FK1" FOREIGN KEY ("CASELOAD_ID", "USERNAME") REFERENCES "USER_ACCESSIBLE_CASELOADS" ("CASELOAD_ID", "USERNAME"),
  CONSTRAINT "USER_CASELOAD_ROLES_FK2" FOREIGN KEY ("ROLE_ID") REFERENCES "OMS_ROLES" ("ROLE_ID")
);

CREATE INDEX "USER_CASELOAD_ROLES_FK1"
  ON "USER_CASELOAD_ROLES" ("CASELOAD_ID", "USERNAME");
CREATE INDEX "USER_CASELOAD_ROLES_FK2"
  ON "USER_CASELOAD_ROLES" ("ROLE_ID");


create table V_TAG_DBA_USERS (
  USERNAME              VARCHAR2(30)  not null,
  ACCOUNT_STATUS        VARCHAR2(255) not null,
  CREATED               timestamp     not null,
  EXPIRED_FLAG          char(1)       not null,
  EXPIRY_DATE           timestamp,
  LOCK_DATE             timestamp,
  LOCKED_FLAG           char(1)       not null,
  LOGGED_IN             char(1)       not null,
  PROFILE               VARCHAR2(255),
  USER_TYPE_DESCRIPTION VARCHAR2(255),
  primary key (USERNAME)
);

