# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/hmpps-auth
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080
  livenessProbePath: /auth/health/liveness
  readinessProbePath: /auth/health/readiness

mfa_whitelist:
  office: "217.33.148.210/32"
  mojvpn: "81.134.202.29/32"

env:
  APPLICATION_SUPPORT_URL: "https://support-dev.hmpps.service.justice.gov.uk/feedback-and-support"
